### PR TITLE
Code cleanup and refactor

### PR DESCRIPTION
**Pull request by Quixotic7**
This PR splits up the functionality contained in OMX-27-firmware.ino into several classes. 

The goal of this refactor is to organize and structure the code to make it easier to add new features and modes and increase readability. 

No additional features have been added and functionality is the same as main. 

Each mode now has it's own class where it's logic is defined. The base abstract class OmxModeInterface is used to define an interface for an OMX Mode. The sequencer and midi mode logic was split into their own classes: OmxModeSequencer and OmxModeMidiKeyboard. Since the difference between S1 and & S2 modes is minimal, both modes use the same class and a bool is set depending on the mode. The difference between OM and MI modes is also minimal, so a bool is used to set the Midi mode to Organelle mode. 

Big switch logic was removed and replaced with function calls to the activeOmxMode which points at the class of the current mode. The function changeOmxMode() handles switching the pointer. 

Since lots of variables are shared between the sequencer and midi modes, I've moved these into global structs in config.h so they can be easily accessed from any of the modes. 

Specific shared code for updating the LEDs, Display, Midi, CV were moved into OmxDisp, OmxLeds, and OmxUtil. These each declare a global instance of themselves in their headers. 

The screensaver code was also moved into it's own class OmxScreensaver

The Midi modes and Sequencer modes can still be cleaned up quite a lot has they have some very long functions, but at least they are self contained so all their logic is in one place. 

Please pull branch, build, test and let me know any issues before merging. Thanks.

### CODE REVIEW

**Comment by catkins** [comment]
Nice refactoring! I was slowly chipping away at a similar approach at the end of last yeah. I'm a big fan of the replace conditional with polymorphism refactoring technique. 👌 

My main nitpick would be that rather than having the global state shared via config.h and using externs, it would feel cleaner (to me) if each of the new classes accepted their dependencies as explicitly constructor arguments. This would make the lifecycle of each object/struct very clear, and be self-documenting in terms of understanding which things need each right. In turn, this would help untangle any circular dependencies between them and help in reducing coupling. 

Nice work!

**Comment by Quixotic7** [comment]
Thanks for your review! 

The global state variables were done because a lot of the features have cross-interaction. Some of these can definitely be moved to the mode classes themselves. I didn't want to dive too deep into dissecting the sequencer yet, so I left some of this cleanup for later modifications. 

Main goal here was a general high-level organization and cleanup. Still much can be improved, like having a page manager.

**Review by okyeron — APPROVED** [review]
Looks OK to my not-so-smart eyes. :-P

Should we just merge it and do more testing as we add the other new features?

**Comment by Quixotic7** [comment]
Merge is fine by me. Or we could merge to a dev branch since.

**Pull request merged**
